In [1]:
import pandas as pd

import numpy as np

In [2]:
data = pd.read_csv('iris.csv')

In [3]:
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
data['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [11]:
x = data.iloc[:,0:4].values

In [12]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
y = data.iloc[:,-1]

In [14]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [18]:
print("that is X_train")
print("")
print(x_train)
print("that is X_test")
print("")
print(x_test)
print("that is ytrain")
print("")
print(y_train)
print("that is y_test")
print("")
print(y_test)

print("")

print("process has been done")


that is X_train

[[4.7 3.2 1.6 0.2]
 [7.  3.2 4.7 1.4]
 [4.6 3.2 1.4 0.2]
 [6.3 2.5 4.9 1.5]
 [5.  3.  1.6 0.2]
 [7.3 2.9 6.3 1.8]
 [5.9 3.2 4.8 1.8]
 [6.  2.2 4.  1. ]
 [5.  3.4 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.1 3.  4.9 1.8]
 [5.  3.3 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [5.9 3.  5.1 1.8]
 [5.8 2.7 5.1 1.9]
 [7.2 3.  5.8 1.6]
 [6.  2.9 4.5 1.5]
 [6.2 2.9 4.3 1.3]
 [4.4 3.  1.3 0.2]
 [5.5 4.2 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [6.7 3.3 5.7 2.5]
 [5.  3.4 1.6 0.4]
 [7.6 3.  6.6 2.1]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [6.3 3.3 6.  2.5]
 [5.1 3.7 1.5 0.4]
 [4.9 2.5 4.5 1.7]
 [5.7 2.8 4.5 1.3]
 [5.6 2.5 3.9 1.1]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [6.1 2.8 4.7 1.2]
 [4.6 3.6 1.  0.2]
 [7.7 3.  6.1 2.3]
 [6.4 3.2 5.3 2.3]
 [6.4 3.2 4.5 1.5]
 [4.6 3.4 1.4 0.3]
 [5.5 2.6 4.4 1.2]
 [5.7 2.6 3.5 1. ]
 [6.8 3.  5.5 2.1]
 [4.4 2.9 1.4 0.2]
 [6.4 2.8 5.6 2.1]
 [5.5 2.3 4.  1.3]
 [6.3 3.3 4.7 1.6]
 [6.1 2.6 5.6 1.4]
 [5.1 3.5 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [5.4 3.4 1.7 0.2]
 [6.9 3.1 5.4 2.1]
 [4.9 3.1 1.5 

In [22]:
import plotly.express as px


In [23]:
fg =px.line(x,y)
fg.show()

In [29]:
from sklearn.svm import SVC

In [31]:
s = SVC(kernel='linear')

In [33]:
s.fit(x_train,y_train)

SVC(kernel='linear')

In [34]:
s.score(x_test,y_test)

1.0

In [35]:
s.predict(x_test)

array(['virginica', 'setosa', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'virginica', 'versicolor', 'virginica',
       'virginica', 'virginica', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'virginica', 'setosa', 'virginica', 'setosa',
       'versicolor', 'virginica', 'virginica', 'setosa', 'versicolor'],
      dtype=object)

In [36]:
x_train

array([[4.7, 3.2, 1.6, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [4.6, 3.2, 1.4, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5. , 3. , 1.6, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [5.9, 3.2, 4.8, 1.8],
       [6. , 2.2, 4. , 1. ],
       [5. , 3.4, 1.5, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.3, 1.4, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [7.2, 3. , 5.8, 1.6],
       [6. , 2.9, 4.5, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5. , 3.4, 1.6, 0.4],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.5, 1.6, 0.6],
       [6.3, 3.3, 6. , 2.5],
       [5.1, 3.7, 1.5, 0.4],
       [4.9, 2.5, 4.5, 1.7],
       [5.7, 2.8, 4.5, 1.3],
       [5.6, 2.5, 3.9, 1.1],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.1, 2.8, 4.7, 1.2],
       [4.6, 3